#!/usr/bin/env python3
# © Copyright 2025-2026, Query.Farm LLC - https://query.farm
# SPDX-License-Identifier: Apache-2.0

"""Generate launcher hash parity vectors as a C++ header.

The vgi DuckDB extension (~/Development/vgi) ships a C++ port of the launcher
that must produce byte-identical hashes to ``vgi_rpc.launcher.compute_hash``
so that workers spawned by ``vgi-rpc launch`` and the C++ launcher share the
same warm worker.

This script regenerates the golden vector header that the C++ unit-test
binary asserts against.  Run after any change to the Python launcher's hash
input format:

    uv run python scripts/regenerate_launcher_parity_vectors.py \\
        > ~/Development/vgi/test/cpp/launcher_parity_vectors.hpp
"""

from __future__ import annotations

import dataclasses
import hashlib
import json
import sys
from collections.abc import Mapping


@dataclasses.dataclass(frozen=True)
class Case:
    """A single parity vector input."""

    name: str
    argv: tuple[str, ...]
    cwd: str
    env: Mapping[str, str]


CASES: tuple[Case, ...] = (
    Case("empty_argv_empty_env", (), "/tmp", {}),
    Case("single_arg", ("python",), "/tmp", {}),
    Case("many_args", ("python", "-m", "foo", "--bar", "baz"), "/tmp", {}),
    Case("argv_with_spaces", ("python", "/path with spaces/foo.py"), "/tmp", {}),
    Case("cwd_with_special_chars", ("python",), "/tmp/has spaces and \"quotes\"", {}),
    Case("env_single", ("python",), "/tmp", {"VGI_RPC_FOO": "bar"}),
    Case(
        "env_multiple_sorted_by_python",
        ("python",),
        "/tmp",
        {"VGI_RPC_Z": "z", "VGI_RPC_A": "a", "VGI_RPC_M": "m"},
    ),
    Case(
        "env_with_quotes_and_backslash",
        ("python",),
        "/tmp",
        {"VGI_RPC_FOO": 'a"b\\c'},
    ),
    Case(
        "env_value_with_spaces",
        ("python",),
        "/tmp",
        {"VGI_RPC_FLAG": "value with spaces"},
    ),
    Case(
        "argv_with_quotes_and_backslash",
        ("echo", 'a"b\\c'),
        "/tmp",
        {},
    ),
    Case(
        "long_path",
        ("/usr/local/bin/very/long/path/to/the/worker/executable",),
        "/tmp",
        {},
    ),
    Case(
        "deep_cwd",
        ("python",),
        "/var/folders/5z/abcdefghijklmnop/T/working/directory/deep/nesting",
        {},
    ),
    Case(
        "many_args_many_env",
        ("java", "-jar", "/opt/foo.jar", "-Dlog.level=INFO"),
        "/var/folders/work",
        {
            "VGI_RPC_TOKEN": "secret",
            "VGI_RPC_REGION": "us-west-2",
            "VGI_RPC_BUCKET": "my-bucket",
        },
    ),
)


def canonical_json(case: Case) -> str:
    """Build the canonical JSON the launcher hashes."""
    payload = {
        "cmd": list(case.argv),
        "cwd": case.cwd,
        "env": dict(case.env),
    }
    return json.dumps(payload, sort_keys=True, separators=(",", ":"))


def compute_hash(case: Case) -> str:
    return hashlib.sha256(canonical_json(case).encode("utf-8")).hexdigest()[:16]


def cpp_string_literal(s: str) -> str:
    """Emit a C++ raw-string-safe quoted literal."""
    out = ['"']
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ord(ch) < 0x20 or ord(ch) > 0x7E:
            out.append(f"\\x{ord(ch):02x}")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def emit_header() -> str:
    lines: list[str] = []
    lines.append("// AUTO-GENERATED by vgi-rpc/scripts/regenerate_launcher_parity_vectors.py")
    lines.append("// DO NOT EDIT BY HAND.  Re-run the generator and commit the result.")
    lines.append("//")
    lines.append("// Each vector pins the byte-identical hash that")
    lines.append("// vgi_rpc.launcher.compute_hash() produces for the given (argv, cwd,")
    lines.append("// env) tuple.  The C++ ComputeLauncherHash() must match every entry.")
    lines.append("")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <map>")
    lines.append("#include <string>")
    lines.append("#include <vector>")
    lines.append("")
    lines.append("namespace duckdb::vgi::launcher::test {")
    lines.append("")
    lines.append("struct ParityVector {")
    lines.append("\tconst char *name;")
    lines.append("\tstd::vector<std::string> argv;")
    lines.append("\tstd::string cwd;")
    lines.append("\tstd::map<std::string, std::string> env;")
    lines.append("\tconst char *expected_hash;")
    lines.append("};")
    lines.append("")
    lines.append("inline const std::vector<ParityVector> &PythonParityVectors() {")
    lines.append("\tstatic const std::vector<ParityVector> kVectors = {")
    for case in CASES:
        h = compute_hash(case)
        argv_lit = ", ".join(cpp_string_literal(a) for a in case.argv)
        env_lit = ", ".join(
            f"{{{cpp_string_literal(k)}, {cpp_string_literal(v)}}}" for k, v in case.env.items()
        )
        lines.append("\t    {")
        lines.append(f"\t        /*name=*/{cpp_string_literal(case.name)},")
        lines.append(f"\t        /*argv=*/{{{argv_lit}}},")
        lines.append(f"\t        /*cwd=*/{cpp_string_literal(case.cwd)},")
        lines.append(f"\t        /*env=*/{{{env_lit}}},")
        lines.append(f"\t        /*expected_hash=*/{cpp_string_literal(h)},")
        lines.append("\t    },")
    lines.append("\t};")
    lines.append("\treturn kVectors;")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace duckdb::vgi::launcher::test")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    sys.stdout.write(emit_header())
